### ISSUE TITLE
Jekyll Push Consumes Too Much Operations

### ISSUE THREAD

**Issue by ghost** [algolia/algoliasearch-jekyll#23]
I am using an Algolia Hacker plan and using Travis to build my Jekyll site. The site will get rebuild whenever there is a new post which happens multiple times a day. 

Currently, my site has around 300+ posts which mean every time Travis build the site and invoke `Jekyll algolia push` it will consume at least 300+ operations.

My question is, is there a way to delta update the index instead of whole update index all over again? So that I can save some operations for real search and not waste so many operations on re-index preexist stuff.

**Comment by pixelastic** [comment]
Hello,

Currently there is not built-in way inside the plugin to do that. It blindly pushes all records to a temporary index, then override the previous index with the new one, without keeping any record of the previous state.

A way to implement that would be to create a custom `objectID` for each record pushed, that will be a hash of its content. That way if the content changes, the objectID will change as well. When pushing data, we would just have to compare the list of items we are about to push with the list of items already in the index. We'll remove the one that are in the index but not in local, and add the one we have locally but not in the index. Every other record will already be in the index, so no need to push them.

To get the list of records already in the index, we could use the [browse method of the API](https://www.algolia.com/doc/ruby#backup--export-an-index) or a local cache. For your specific case, the `browse` method will be better because Travis won't keep a local cache on its side.

This is actually a very valid concern, I will try to address that in the next version. As of today, while it is still possible to build the logic I explained using the hooks provided by the plugin, it might be a bit complex.

**Comment by pixelastic** [comment]
I've added the `lazy_update` option in the `v1` branch. When set to true, it will:
- Delete records in the index that are no longer in the local version
- Push records in the local version that are not yet in the index
- Do nothing for all the other records

This should greatly reduce the number of operations used. The drawback is that it won't be an atomic update (ie. you can have your data in an inconsistent state for a short while, with records deleted but new one not yet added).

**Comment by pixelastic** [comment]
I'm closing this issue as I plan on releasing the v1 branch officially soon.
