### ISSUE TITLE
Content not rendered with Liquid before indexing?

### ISSUE THREAD

**Issue by bomberstudios** [algolia/algoliasearch-jekyll#42]
Hi there,

I have a Jekyll site that uses the https://github.com/rustygeldmacher/jekyll-contentblocks plugin, and also some `{% include … %}` blocks. I was experimenting with the Algolia search plugin, and found out that it wasn't processing Liquid blocks on my content.

I have replaced

```rb
document = Nokogiri::HTML(@file.content)
```

with

```rb
content = Jekyll::Renderer.new(@file.site, @file).run
document = Nokogiri::HTML(content)
```

on `lib/record_extractor.rb` so that my content is fully rendered.

I understand this is not always the best approach (specially if you don't use Liquid on your content) since it slows the processing and renders more stuff than it's usually needed (headers and footers, etc…)

So I was wondering if you'd accept a PR that would check a setting (something like `render_full_page`) and render full pages (instead of just the content of each page / post).

**Comment by pixelastic** [comment]
Hello,

The plugin is supposed to simulate a `jekyll build`, but intercept files before they are written on disk and push the content to Algolia instead. I thought it would catch every possible plugin application, but apparently there are other sneaky ways :)

I would be very interested in your PR, especially if you can add some tests for this behavior. That being said, I have been working on an official v1 of the plugin (you can find it in the `v1` branch, as well as on rubygems) where I rewrote a big part of the plugin. Have you tried this version?

If you can submit your PR on `v1` it would be awesome, otherwise you can submit it to `master` and I will handle moving it to `v1` in due time. Same for tests, if you have them, it's perfect, otherwise I'll add them.

**Comment by pixelastic** [comment]
Hey @bomberstudios, did you had a chance to work on this PR?

**Comment by bomberstudios** [comment]
Sorry, life happened! I'll see if I can find the time to polish & share my code!

**Comment by pixelastic** [comment]
No problem and don't apologize, I totally understand. Just know that your participation will be appreciated if you decide to submit a PR, but I totally understand if you don't want to or don't have time :)

**Comment by pixelastic** [comment]
Thanks for the PR @bomberstudios. 

I unfortunately won't be able to accept it directly as the code to actually extract records from HTML pages has been moved to another gem and the main plugin has now moved to [jekyll-algolia](https://github.com/algolia/jekyll-algolia).

I'm still interested in getting this issue fixed though. Would it be possible for you to share a repo where I could reproduce the issue? I'll then port your PR to the relevant repos.

Thanks a lot

**Comment by pixelastic** [comment]
I'm closing this issue for now. Feel free to re-open it if you're experiencing similar issues with jekyll-algolia. 

Thanks the PR!
