### ISSUE TITLE
Reduce the number of entries

### ISSUE THREAD

**Issue by borisschapira** [algolia/algoliasearch-jekyll#8]
Algolia is registering a lot more entries that I have posts. I think that multiple entries are created for a post, based on the number of paragraphs. Is it possible to desactivate paragraph targeting in order to match a post with an object ?

**Comment by pixelastic** [comment]
Hello,

The plugin currently create a record for each `p` of your entries. This is done in order to have a good relevance on the results. If we were to index the whole content in one record, when you start searching for `foo bar`, you would match every entry with `foo` at the start and `bar` at the end. Splitting by paragraph (and grouping by url) let us always have a nice relevance.

You can tweak this if you want, by editing the [agolia.record_css_selector](https://github.com/algolia/algoliasearch-jekyll#record_css_selector) entry in your `_config.yml` file. If you set it to `h1,h2,h3,h4` for example, it will only index the various headers of your posts, and not the paragraphs.

As said earlier, this means that you will no longer be able to search for content in the `p`, but depending on your use-case this might be what you're looking for.

**Comment by borisschapira** [comment]
Hum ok, so I'll need to remove some posts from borisschapira.com if I want to respect the 1000-entry limit of the Hacker Plan. Thanks for the explanation :)

**Comment by pixelastic** [comment]
As a side note, you can use the [AlgoliaSearchRecordExtractor.custom_hook_each](https://github.com/algolia/algoliasearch-jekyll#hooks) hook to have more control on which record should be pushed and which should not. If you return `nil`, it won't be pushed.
